### ISSUE TITLE
Something wrong with my decryption

### ISSUE THREAD

**Issue by Tdyh** [ceceww/aes#1]
I don't know if it was my fault . But I met some problem in decryption. there alaways gonna be some choas code in the decrypt message . I hope you know what i mean. 
like this:
=============================
 128-bit AES Decryption Tool
=============================
Read in encrypted message from message.aes
Read in the 128-bit key from keyfile
Decrypted message in hex:
48 41 48 41 0 0 0 0 0 0 0 0 0 0 0 0 54 f2 b7 74 2f 78
Decrypted message: HAHA            T蚍t/x

But the real info is "HAHA"  
Could you please let me know if you solve this problem 
Thank you!

**Comment by CHarrison7** [comment]
I'm getting something similar...


MacBook-Pro:aes caleb$ ./encrypt
=============================
 128-bit AES Encryption Tool   
=============================
Enter the message to encrypt: Caleb
Caleb
Encrypted message in hex:
6e d5 a6 18 aa 8d b5 b8 a9 9c aa d cb 4a c3 8f 


Wrote encrypted message to file message.aes



MacBook-Pro:aes caleb$ ./decrypt
=============================
 128-bit AES Decryption Tool 
=============================
Read in encrypted message from message.aes
Read in the 128-bit key from keyfile
Decrypted message in hex:
43 61 6c 65 62 0 0 0 0 0 0 0 0 0 0 0 bf ed 78 ed 50 36 b0 82 6 d0 b3 36 20 bc 7b 5c 35 c1 cb a7 d cc b8 ab 78 cf 3a d5 f8 7e 4c 4b e6 2c ba 60 b 7d 4f 76 83 75 56 67 ec b 7a 



Decrypted message: 
̸?x?:??~LK?,?`г6 ?{\5?˧
             }Ov?uVg?
                     z

MacBook-Pro:aes caleb$

**Comment by deulis** [comment]
Maybe is too late to response, but anyway...

Tdyh, the AES encryption and description works in block of 16 bytes, that means if you have a message lest that 16 bytes to encrypt it you need to complete until 16 byte length, usually you need to add zero to the end of you message to achieve 16 bytes or the next number that is multiples of 16. So when you decrypts you need to remove the bytes you added at the end of you original message.

**Comment by Tdyh** [comment]
> Maybe is too late to response, but anyway...
> 
> Tdyh, the AES encryption and description works in block of 16 bytes, that means if you have a message lest that 16 bytes to encrypt it you need to complete until 16 byte length, usually you need to add zero to the end of you message to achieve 16 bytes or the next number that is multiples of 16. So when you decrypts you need to remove the bytes you added at the end of you original message.

Oops,  I should'v thought about it. The problem is I didn't add zero to meet 16bytes.  This was kind 
 of my homework actually. But thanks anyway.

**Comment by Tdyh** [comment]
you'v been very helpful!!!
